services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 768M
        reservations:
          memory: 512M
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JWT_SECRET=${SPRING_JWT_SECRET}
      - SPRING_JWT_ACCESS_EXPIRATION=${SPRING_JWT_ACCESS_EXPIRATION}
      - SPRING_JWT_REFRESH_EXPIRATION=${SPRING_JWT_REFRESH_EXPIRATION}
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 1.5G
        reservations:
          memory: 1G
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          memory: 512M
    restart: unless-stopped

volumes:
  db-data:
