spring:
  application:
    name: iload-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
      timezone:
        default_storage: NORMALIZE
      jdbc:
        time_zone: UTC
  security:
    cors:
      allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS:http://localhost:8080}
    jwt:
      access-token:
        secret-key: ${SPRING_JWT_SECRET}
        expiration: ${SPRING_JWT_ACCESS_EXPIRATION}
      refresh-token:
        secret-key: ${SPRING_JWT_SECRET}
        expiration: ${SPRING_JWT_REFRESH_EXPIRATION}
  s3:
    endpoint: ${SPRING_S3_ENDPOINT}
    bucket: ${SPRING_S3_BUCKET}
    access-key: ${SPRING_S3_ACCESS_KEY}
    secret-key: ${SPRING_S3_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/docs
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
    operationsSorter: alpha
    tagsSorter: alpha
    try-it-out-enabled: true
    oauth:
      useBasicAuthenticationWithAccessCodeGrant: true
