spring:
  application:
    name: iload-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  security:
    cors:
      allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS:http://localhost:3000}
    jwt:
      access-token:
        secret-key: ${SPRING_JWT_SECRET}
        expiration: ${SPRING_JWT_ACCESS_EXPIRATION}
      refresh-token:
        secret-key: ${SPRING_JWT_SECRET}
        expiration: ${SPRING_JWT_REFRESH_EXPIRATION}

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/docs
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
    operationsSorter: alpha
    tagsSorter: alpha
    try-it-out-enabled: true
    oauth:
      useBasicAuthenticationWithAccessCodeGrant: true
